exclude: '^$|settings|scripts|docs'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
        exclude: |
            (?x)^(
                .*README.md|
                .*\.f90
            )$
        # let flake8 deal with py => dont treat docstrings.
        exclude_types: ['html','python']
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
        exclude: 'dapper/tools/liveplotting.py'
    -   id: detect-aws-credentials  # Notifies if you DONT have credentials
        args:
        - --allow-missing-credentials
    -   id: detect-private-key  # Notifies if you have private
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: ['--fix=no']

-   repo: https://github.com/flakeheaven/flakeheaven
    rev: 0.11.0
    hooks:
    -   id: flakeheaven
        additional_dependencies: [
          flake8-docstrings,
          flake8-bugbear,
          flake8-comprehensions,
          flake8-isort,
          flake8-builtins,
          pep8-naming,
        ]

-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        exclude: |
            (?x)^(
                examples/.*.py
            )$
